import dotenv from "dotenv"

dotenv.config()


export const envVars = {
    PORT: process.env.PORT,
    FRONTEND_URL: process.env.FRONTEND_URL,
    MONGODB_URL: process.env.MONGODB_URL,
    NODE_ENV: process.env.NODE_ENV,

    SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
    SUPER_ADMIN_PASSWORD:process.env.SUPER_ADMIN_PASSWORD,

    HASH_SALT: process.env.HASH_SALT,

    CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME as string,
    CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY as string,
    CLOUDINARY_SECRET_KEY:process.env.CLOUDINARY_SECRET_KEY as string,



JWT_SECRET: process.env.JWT_SECRET,
JWR_EXPIRED:process.env.JWR_EXPIRED,

JWT_REFRESH_SECRET:process.env.JWT_REFRESH_SECRET,

JWT_REFRESH_EXPIRED:process.env.JWT_REFRESH_EXPIRED,

SSL: {

    SSL_STORE_ID:process.env.SSL_STORE_ID,
    SSL_STORE_PASS:process.env.SSL_STORE_PASS,
    SSL_PAYMENT_API:process.env.SSL_PAYMENT_API,
    SSL_VALIDATION_API:process.env.SSL_VALIDATION_API,
    SSL_SUCCESS_FRONTEND_URL:process.env.SSL_SUCCESS_FRONTEND_URL,
    SSL_FAIL_FRONTEND_URL:process.env.SSL_FAIL_FRONTEND_URL,
    SSL_CANCEL_FRONTEND_URL:process.env.SSL_CANCEL_FRONTEND_URL,
    SSL_SUCCESS_BACKEND_URL:process.env.SSL_SUCCESS_BACKEND_URL,
    SSL_FAIL_BACKEND_URL:process.env.SSL_FAIL_BACKEND_URL,
    SSL_CANCEL_BACKEND_URL:process.env.SSL_CANCEL_BACKEND_URL,
    SSL_VALIDATE_IPN: process.env.SSL_VALIDATE_IPN
},
}